name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - numpy
  - matplotlib
  - pandas
  - altair
  # - vegafusion These do not run because they need pyarrow which is not supported in xeus (among others?)
  # - vegafusion-jupyter
